wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.2
    cli_version: 0.16.6
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717501086.0
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 103
      - 105
      2:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 103
      - 105
      3:
      - 23
      4: 3.9.2
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
